global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
  - job_name: "ai-analyzer"
    static_configs:
      - targets: ["ai-analyzer:8000"]
